export const PERMS = {
  // EMPLOYEES
  EMPLOYEE_VIEW: "EMPLOYEE:VIEW",
  EMPLOYEE_HIRE: "EMPLOYEE:HIRE",
  EMPLOYEE_UPDATE: "EMPLOYEE:UPDATE",
  EMPLOYEE_INCREASE_SALARY: "EMPLOYEE:INCREASE_SALARY",
  EMPLOYEE_REINSTATE: "EMPLOYEE:REINSTATE",
  EMPLOYEE_SUSPEND: "EMPLOYEE:SUSPEND",
  EMPLOYEE_TERMINATE: "EMPLOYEE:TERMINATE",
  EMPLOYEE_PAY: "EMPLOYEE:PAY",
  EMPLOYEE_VIEW_WORK_HISTORY: "EMPLOYEE:VIEW_WORK_HISTORY",
  EMPLOYEE_VIEW_PAYMENT_HISTORY: "EMPLOYEE:VIEW_PAYMENT_HISTORY",

  // POSITIONS
  POSITION_VIEW: "POSITION:VIEW",
  POSITION_CREATE: "POSITION:CREATE",
  POSITION_EDIT: "POSITION:EDIT",
  POSITION_ACTIVATE: "POSITION:ACTIVATE",
  POSITION_DEACTIVATE: "POSITION:DEACTIVATE",

  // ROLES
  ROLE_VIEW: "ROLE:VIEW",
  ROLE_CREATE: "ROLE:CREATE",
  ROLE_EDIT: "ROLE:EDIT",
  ROLE_ACTIVATE: "ROLE:ACTIVATE",
  ROLE_DEACTIVATE: "ROLE:DEACTIVATE",

  // USERS
  USER_VIEW: "USER:VIEW",
  USER_CHANGE_ROLE: "USER:CHANGE_ROLE",

  // PROJECTS
  PROJECT_VIEW: "PROJECT:VIEW",
  PROJECT_CREATE: "PROJECT:CREATE",
  PROJECT_CLOSE: "PROJECT:CLOSE",
  PROJECT_OPEN: "PROJECT:OPEN",
  PROJECT_PAY: "PROJECT:PAY",
  PROJECT_VIEW_PAYMENT_HISTORY: "PROJECT:VIEW_PAYMENT_HISTORY",

  // SPRINTS
  SPRINT_CREATE: "SPRINT:CREATE",
  SPRINT_START: "SPRINT:START",
  SPRINT_COMPLETE: "SPRINT:COMPLETE",
  SPRINT_DELETE: "SPRINT:DELETE",

  // REPORTS
  REPORT_PROJECT_PROGRESS: "REPORT:PROJECT_PROGRESS",
  REPORT_HIRING_HISTORY: "REPORT:HIRING_HISTORY",
  REPORT_TERMINATION_HISTORY: "REPORT:TERMINATION_HISTORY",
  REPORT_ROLE_GENERAL: "REPORT:ROLE_GENERAL",
  REPORT_INCOMES: "REPORT:INCOMES",
  REPORT_PROFITS: "REPORT:PROFITS",
  REPORT_EXPENSES: "REPORT:EXPENSES",

} as const;

export type PermissionCode = typeof PERMS[keyof typeof PERMS];
