export const PERMS = {
  // EMPLOYEES
  EMPLOYEE_VIEW: "EMPLOYEE:VIEW",
  EMPLOYEE_HIRE: "EMPLOYEE:HIRE",
  EMPLOYEE_UPDATE: "EMPLOYEE:UPDATE",
  EMPLOYEE_INCREASE_SALARY: "EMPLOYEE:INCREASE_SALARY",
  EMPLOYEE_REINSTATE: "EMPLOYEE:REINSTATE",
  EMPLOYEE_SUSPEND: "EMPLOYEE:SUSPEND",
  EMPLOYEE_TERMINATE: "EMPLOYEE:TERMINATE",
  EMPLOYEE_PAY: "EMPLOYEE:PAY",
  EMPLOYEE_VIEW_WORK_HISTORY: "EMPLOYEE:VIEW_WORK_HISTORY",
  EMPLOYEE_VIEW_PAYMENT_HISTORY: "EMPLOYEE:VIEW_PAYMENT_HISTORY",

  // POSITIONS
  POSITION_VIEW: "POSITION:VIEW",
  POSITION_CREATE: "POSITION:CREATE",
  POSITION_EDIT: "POSITION:EDIT",
  POSITION_ACTIVATE: "POSITION:ACTIVATE",
  POSITION_DEACTIVATE: "POSITION:DEACTIVATE",

  // ROLES
  ROLE_VIEW: "ROLE:VIEW",
  ROLE_CREATE: "ROLE:CREATE",
  ROLE_EDIT: "ROLE:EDIT",
  ROLE_ACTIVATE: "ROLE:ACTIVATE",
  ROLE_DEACTIVATE: "ROLE:DEACTIVATE",
} as const;

export type PermissionCode = typeof PERMS[keyof typeof PERMS];
